# Hack-wifi-Fb-insta-gmail-hotmai-

اداه اختراق وايفاي wifi-hacker 
《 جميع الحقوق محفوظة 》
 تحتاج روت 
 《 محمد مهدي من سوريا 》
 m313s@ 
Wifi paswoord wps/2 
نبدأ بنسخ الاوامر ولصق داخل Termux
  apt update   apt upgrade
  apt install git  
  git clone https://github.com/esc0rtd3w/wifi-hacker 
  cd wifi-hacker   
  chmod +x wifi-hacker.sh  
  ./wifi-hacker.sh 

 بالتوفيق....
 #يرجى_ذكر_المصدر  
 @m313s
